Models/Board.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Donatello.Models
{
    public class Board
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<Column> Columns { get; set; } = new List<Column>();
    }

    [Table("Card")]
    public class Card
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public string Notes { get; set; }
        public int ColumnId { get; set; }
        public Column Column { get; set; }
    }

    public class Column
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<Card> Cards { get; set; } = new List<Card>();
        public int BoardId { get; set; }
    }
}

ViewModels/AddCard.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Donatello.ViewModels
{
    public class AddCard
    {
        public int Id { get; set; } // board Id
        [Required]
        public string Contents { get; set; } // card contents
    }
}

ViewModels/BoardList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Donatello.ViewModels
{
    public class BoardList
    {
        public List<Board> Boards { get; set; } = new List<Board>();

        public class Board
        {
            public int Id { get; set; }
            public string Title { get; set; }
        }
    }
}

ViewModels/BoardView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Donatello.ViewModels
{
    public class BoardView
    {
        public int Id { get; set; }
        public List<Column> Columns { get; set; } = new List<Column>();

        public class Column
        {
            public string Title { get; set; }
            public List<Card> Cards { get; set; } = new List<Card>();
        }

        public class Card
        {
            public int Id { get; set; }
            public string Content { get; set; }
        }
    }
}

ViewModels/CardDetails.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Donatello.ViewModels
{
    public class CardDetails
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public string Notes { get; set; }

        public int Column { get; set; }
        public List<SelectListItem> Columns { get; set; } = new List<SelectListItem>();
    }
}

ViewModels/NewBoard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Donatello.ViewModels
{
    public class NewBoard
    {
        public string Title { get; set; }
    }
}

Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Donatello.Services;
using Donatello.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Donatello.Controllers
{
    public class BoardController : Controller
    {
        private readonly BoardService boardService;

        public BoardController(BoardService boardService)
        {
            this.boardService = boardService;
        }

        public IActionResult Index(int id)
        {
            BoardView model = boardService.GetBoard(id);
            return View(model);
        }

        public IActionResult AddCard(int id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCard(AddCard viewModel)
        {
            if (ModelState.IsValid)
            {
                boardService.AddCard(viewModel);
                return RedirectToAction(nameof(Index), new
                {
                    id = viewModel.Id
                });
            }
            return View(viewModel);
        }
    }
}

Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Donatello.Services;
using Donatello.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Donatello.Controllers
{
    public class CardController : Controller
    {
        private readonly CardService cardService;

        public CardController(CardService cardService)
        {
            this.cardService = cardService;
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            CardDetails viewModel = cardService.GetDetails(id);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Details(CardDetails cardDetails)
        {
            cardService.Update(cardDetails);
            TempData["Message"] = "Saved Card Details";
            return RedirectToAction(nameof(Details), new { id = cardDetails.Id });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Donatello.Services;
using Donatello.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Donatello.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class HomeController : Controller
    {
        private readonly BoardService boardService;

        public HomeController(BoardService boardService)
        {
            this.boardService = boardService;
        }

        public IActionResult Index()
        {
            BoardList model = boardService.ListBoards();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(NewBoard viewModel)
        {
            boardService.AddBoard(viewModel);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Board/AddCard.cshtml
@model Donatello.ViewModels.AddCard

<div class="container">
    <div class="row">
        <h2>Add Card</h2>
        <form asp-action="AddCard" asp-controller="Board">
            <div asp-validation-summary="All" class="text-danger"></div>
            <label asp-for="Contents"></label>
            <input type="text" asp-for="Contents" />
            <button type="submit" class="btn">Add it!</button>
        </form>

    </div>
</div>

Views/Board/Index.cshtml
@model Donatello.ViewModels.BoardView
@{
    ViewData["Title"] = "Board View";
}

<div class="container">
    @if (Model.Columns.Count > 0)
    {
        <a asp-controller="Board"
           asp-action="AddCard"
           asp-route-id="@Model.Id"
           class="waves-effect waves-light btn">
            Add Card
        </a>
    }

    <div class="row">
        @foreach (var column in Model.Columns)
        {
            <div class="col m2">
                <h3>@column.Title</h3>

                @foreach (var card in column.Cards)
                {
                    <div class="card blue-grey darken-1">
                        <div class="card-content white-text">                            
                            <p>
                                <a asp-controller="Card" asp-action="Details"
                                   asp-route-id="@card.Id" class="white-text">
                                    @card.Content
                                </a>
                            </p>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
</div>

Views/Card/Details.cshtml
@model Donatello.ViewModels.CardDetails
@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h2>Details</h2>

    <div class="row">
        <form class="col s12" asp-controller="Card" asp-action="Details">
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Card contents"
                           asp-for="Contents" />
                    <label asp-for="Contents">Contents</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <textarea placeholder="Notes"
                              asp-for="Notes"
                              class="materialize-textarea"></textarea>
                    <label asp-for="Notes">Notes</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <select asp-for="Column" asp-items="Model.Columns"></select>
                    <label asp-for="Column">Column</label>
                </div>
            </div>
            <div class="row">
                <input asp-for="Id" type="hidden" />
                <input type="submit" value="Save" class="btn" />
            </div>
        </form>
    </div>
</div>

@if (TempData.ContainsKey("Message"))
{
    <script type="text/javascript">
        M.toast({ html: '@TempData["Message"]' }, 3000);
    </script>
}

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
    });
</script>

Views/Home/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Donatello.ViewModels.NewBoard

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <h2>Add a new Board</h2>
    <form method="post" asp-controller="Home" asp-action="Create">
        <label>Title</label>
        <input type="text" asp-for="Title" />
        <input type="submit" class="btn" />
    </form>
</div>

Views/Home/Index.cshtml
@model Donatello.ViewModels.BoardList

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">
        <h2>Boards</h2>
        <a asp-action="Create" asp-controller="Home"
           class="waves-effect waves-light btn">
            New Board
        </a>
    </div>
    <div class="row">
        @foreach (var board in Model.Boards)
        {
            <div class="card s12">
                <div style="float: left; margin-right: 2em; width: 22em;">
                    <div class="card blue-grey darken-1">
                        <div class="card-content white-text">
                            <span class="card-title">
                                @board.Title
                            </span>
                        </div>

                        <!-- add this bit -->
                        <div class="card-action">
                            <a asp-action="Index" asp-controller="Board"
                               asp-route-id="@board.Id"
                               class="collection-item">View</a>
                        </div>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <link href="/css/site.css" rel="stylesheet" />

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>

    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

</head>
<body>

    <!-- add this -->
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo center">Donatello</a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li>
                    <a asp-controller="Home" asp-action="Index">
                        Boards
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
</body>
</html>